### PR TITLE
Add missing command in netlify.toml

### PR DESCRIPTION
**Pull request by maelle**
@hadley without this command one cannot use the Netlify config for the production build (I've just had the problem).

### CODE REVIEW

**Comment by hadley** [comment]
What exact problem did you have? Were you setting `publishDir` in your config.yaml alread?

**Comment by maelle** [comment]
I ran `use_netlify_toml()` so I was using the template. With the template there's a Hugo command for previews but not for production deploys, so there's no public dir.

https://app.netlify.com/sites/goofy-lewin-b6d57e/deploys/5efaefe7c6b335e7a88f9fcd

**Comment by maelle** [comment]
I suppose I could have entered that command from the interface, not sure why I didn't :thinking: 

* I ran `usethis::use_github()`
* I created the Netlify config file with the function, I commited&pushed it.
* Then from Netlify I added the repo, I clicked without looking too closely at what had been guessed or not about my repo.

Adding the command in the config file means making life easier for careless people like me. :see_no_evil:

**Comment by hadley** [comment]
Ah ok, I _think_ the command should just be `hugo` though. I had assumed that netlify would set that automatically, but I now don't see how that could be possible.

**Comment by hadley** [comment]
Thanks @maelle!

**Pull request merged**
