### PR TITLE
Eliminate extraneous newlines

### PR DESCRIPTION
**Pull request by jennybc**
Experimentation relating to #91 

This seems to help, which confirms the `knit_hooks` hypothesis. It is also clear I am not the best one to fix this definitively, so I'm stopping here.

### CODE REVIEW

**Comment by hadley** [comment]
I'm pretty sure this is correct. I guess it has always been wrong and we just somehow failed to notice? (Or complain loudly enough that I noticed 😀)

**Comment by jennybc** [comment]
I've got some gratuitous assignments here now, but they were helpful in the debugger.

**Comment by hadley** [comment]
Confirmed that this fixes the problem in the usethis blog post

**Comment by hadley** [comment]
I spoke too soon 😢

**Pull request merged**
